name = "playreportautoposter"
main = "index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/30 * * * *"]

[vars]
# These are placeholders. Cloudflare will replace them.
API_FOOTBALL_KEY = ""
FB_PAGE_TOKEN = ""
FB_PAGE_ID = ""